In [ ]:
!pip install -U sentence-transformers
from sentence_transformers import SentenceTransformer
import numpy as np
import logging

# Load Sentence model (based on BERT) from URL
model = SentenceTransformer('distiluse-base-multilingual-cased-v2')

In [ ]:
model.encode(['o ladrão atacou a polícia'])

array([[-1.98440789e-03,  5.30687021e-03,  2.72244383e-02,
        -1.61122084e-02,  3.19066755e-02, -5.44237643e-02,
        -2.95882504e-02,  5.93010942e-03,  1.77456271e-02,
         1.59953572e-02,  4.66177873e-02,  2.15869825e-02,
        -1.06133884e-02,  7.51019409e-03, -1.49740241e-02,
        -4.01916690e-02, -3.41512747e-02, -4.94553195e-03,
         4.71173711e-02,  9.54928696e-02,  7.71677913e-03,
         1.63166560e-02,  7.51108676e-02,  2.61695012e-02,
        -2.36456133e-02,  4.34750505e-02, -5.10799885e-02,
        -6.39447421e-02, -4.04595658e-02, -2.15198807e-02,
        -3.24586872e-05,  3.23157236e-02, -4.45976183e-02,
        -2.04429757e-02,  3.65424417e-02, -4.02945206e-02,
        -7.69619597e-03,  2.69838497e-02,  4.77386415e-02,
        -7.74894282e-02, -6.27106577e-02, -2.98861582e-02,
        -4.00052294e-02,  2.32239142e-02, -3.57564054e-02,
         1.22855566e-02,  4.49147187e-02, -2.38830689e-02,
         2.74204575e-02,  3.06024812e-02, -3.84205393e-0

In [ ]:
model.encode(['o ladrão atirou na polícia'])

array([[ 0.04098233,  0.01098784,  0.01424083, -0.01735286,  0.01787993,
        -0.06676959, -0.03151984,  0.01445125,  0.0234232 ,  0.02097652,
         0.04619982,  0.03354109,  0.00405034, -0.02817175, -0.0283676 ,
        -0.04102994, -0.03109342,  0.01542995,  0.05240401,  0.07987197,
         0.00862354,  0.01705394,  0.07083623,  0.01570942, -0.01749614,
         0.00541188, -0.05999621, -0.06067194, -0.04948888, -0.03264488,
         0.00091898,  0.01984812, -0.05937398, -0.01732469,  0.04740556,
        -0.03440723, -0.01708691,  0.00953706,  0.05256414, -0.07682517,
        -0.03979424, -0.01718076, -0.06640145,  0.00759927, -0.04198442,
        -0.00317719,  0.04543162, -0.03212513,  0.01594968,  0.02570478,
        -0.03876404,  0.02049666,  0.05032209,  0.00252184,  0.0203181 ,
         0.05468079, -0.06559459,  0.00897202, -0.004027  , -0.01209271,
        -0.04024412,  0.04965627,  0.03975092, -0.03020676,  0.02224825,
         0.09877603,  0.03162085,  0.00973427,  0.0

In [ ]:
model.encode(['a polícia atacou o ladrão'])

array([[ 0.00463937,  0.00781027,  0.02456233, -0.01848532,  0.02449673,
        -0.05619824, -0.03045993,  0.00888761,  0.01374498,  0.01538969,
         0.04833712,  0.02327692, -0.01159078,  0.00792971, -0.00807999,
        -0.03765552, -0.04512732, -0.00583224,  0.04501394,  0.09086774,
         0.00878772,  0.0180367 ,  0.07810476,  0.02569766, -0.02366799,
         0.04278721, -0.04916057, -0.06752679, -0.0421013 , -0.02875004,
         0.00679577,  0.03022401, -0.04557546, -0.01762466,  0.03764451,
        -0.03538563, -0.00452769,  0.02338716,  0.04629922, -0.07444262,
        -0.06464156, -0.02709492, -0.03524975,  0.01831665, -0.03606056,
         0.00669839,  0.04399742, -0.02223798,  0.02075793,  0.03010335,
        -0.0423144 ,  0.0321524 ,  0.04281859,  0.00903906,  0.00361814,
         0.03613651, -0.05294539,  0.00354451,  0.0118867 , -0.03069494,
        -0.03714111,  0.05684525,  0.01884642, -0.02945542,  0.02909144,
         0.09393703,  0.06650535,  0.02859255,  0.0

In [ ]:
model.encode(['Der Dieb griff die Polizei an'])


array([[ 6.90996926e-03,  1.33241189e-03,  4.07548919e-02,
         1.73265825e-03,  3.43604013e-02, -4.18283194e-02,
        -2.45786458e-02,  2.30490835e-03,  1.46938134e-02,
         1.68973971e-02,  2.18320116e-02,  7.79034663e-03,
         2.58237659e-03, -1.36799905e-02, -3.66014019e-02,
        -5.70403086e-03, -3.80845293e-02,  1.53690623e-02,
         2.57704221e-02,  6.51385412e-02, -7.03875069e-03,
         1.98353250e-02,  5.85746653e-02,  1.22125987e-02,
        -2.68399622e-02,  2.39639189e-02, -6.66419119e-02,
        -3.45855393e-02, -1.36315580e-02,  9.17200698e-04,
         3.34856031e-03,  2.12406609e-02, -3.32569890e-02,
        -2.51144283e-02,  1.22796958e-02, -3.00236549e-02,
         3.39777349e-03,  2.40912233e-02,  1.40167614e-02,
        -7.46799409e-02, -4.81280759e-02, -7.52668176e-03,
        -2.69078463e-02,  1.00326873e-02, -4.44699265e-02,
         4.15527858e-02,  5.17974049e-02, -3.15368623e-02,
         2.57963240e-02,  2.44026631e-02, -1.78006347e-0

# Dataset

In [ ]:
!wget https://raw.githubusercontent.com/rmarcacini/text-collections/master/complete_texts_csvs/Dmoz-Health.csv

--2024-09-20 12:36:38--  https://raw.githubusercontent.com/rmarcacini/text-collections/master/complete_texts_csvs/Dmoz-Health.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.110.133, 185.199.111.133, 185.199.109.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.110.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1182768 (1.1M) [text/plain]
Saving to: ‘Dmoz-Health.csv’

Dmoz-Health.csv     100%[===================>]   1.13M  --.-KB/s    in 0.05s   

2024-09-20 12:36:38 (22.5 MB/s) - ‘Dmoz-Health.csv’ saved [1182768/1182768]



In [ ]:
import pandas as pd

dataset = pd.read_csv('Dmoz-Health.csv')

In [ ]:
import numpy as np
from sklearn.model_selection import train_test_split

df_train, df_test = train_test_split(dataset, test_size=0.33, random_state=42)

In [ ]:
df_train

file_name  \
1647       and_Diseases_1594311.txt   
2589             Health_1614027.txt   
1700       and_Diseases_1601766.txt   
5201  Health_and_Safety_1625559.txt   
6004             Health_1628690.txt   
...                             ...   
3772                    1619360.txt   
5191  Health_and_Safety_1624499.txt   
5226  Health_and_Safety_1626228.txt   
5390  Health_and_Safety_1623932.txt   
860                     1583028.txt   

                                                   text        class  
1647  National Eye Institute - The Cornea and Cornea...   Conditions  
2589  Alison Muir - B.A. Hons. Psych. Psychologist l...       Mental  
1700  Talk About Sleep A sleep health community prov...   Conditions  
5201  Arizona Emergency Medical Systems For over 25 ...       Public  
6004  Delaware Nursing Care Center Skilled nursing a...       Senior  
...                                                 ...          ...  
3772  Society for Nutrition Education (SNE) For prof...    Nutrition  
5191  Wabasha Fire Department Stations, equipment, f...       Public  
5226  University of Saskatchewan: Department of Comm...       Public  
5390  Gravenhurst Volunteer Fire Department The GVFD...       Public  
860   New Hampshire Association of Naturopathic Doct...  Alternative  

[4355 rows x 3 columns]

In [ ]:
df_test

file_name  \
3106               1618765.txt   
6161        Health_1629048.txt   
1867  and_Diseases_1596988.txt   
3238               1618104.txt   
5509        Health_1627315.txt   
...                        ...   
2917        Health_1614367.txt   
596                1583133.txt   
6443        Health_1628680.txt   
1068               1583908.txt   
1942  and_Diseases_1599575.txt   

                                                   text         class  
3106  Nurse CEU.com: Pediatrics List of links to Con...       Nursing  
6161  Dementia: A Guide For The Caregiver A guide an...        Senior  
1867  Congenital Toxoplasmosis Includes symptoms, di...    Conditions  
3238  MUSC College of Nursing Medical University of ...       Nursing  
5509  Malpani Infertility Clinic Located in Bombay, ...  Reproductive  
...                                                 ...           ...  
2917  Elizabeth Fadale, LMHC Private practice locate...        Mental  
596   Human Hand - PalmTherapy A review of Palm Ther...   Alternative  
6443  Connecticut Elder Reference Guide Infoline 211...        Senior  
1068  Holistic Stock Health Holistic health care for...        Animal  
1942  The New York University Comprehensive Epilepsy...    Conditions  

[2145 rows x 3 columns]

In [ ]:
# Filtrando o df_train para as classes Senior e Mental
df_train = df_train[df_train['class'].isin(['Senior', 'Mental'])]
df_train['class'] = df_train['class'].map({'Senior': 0, 'Mental': 1})

# Filtrando o df_test para as classes Senior e Mental
df_test = df_test[df_test['class'].isin(['Senior', 'Mental'])]
df_test['class'] = df_test['class'].map({'Senior': 0, 'Mental': 1})


<ipython-input-17-9708688d7747>:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_train['class'] = df_train['class'].map({'Senior': 0, 'Mental': 1})
<ipython-input-17-9708688d7747>:7: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_test['class'] = df_test['class'].map({'Senior': 0, 'Mental': 1})


In [ ]:
df_train

file_name                                               text  \
2589  Health_1614027.txt  Alison Muir - B.A. Hons. Psych. Psychologist l...   
6004  Health_1628690.txt  Delaware Nursing Care Center Skilled nursing a...   
2582  Health_1617262.txt  Behavior OnLine Chat Events Topics of interest...   
2939  Health_1613963.txt  Counsellingsolution.com Provides online counse...   
6056  Health_1628543.txt  Frontier Management Provides assisted living, ...   
...                  ...                                                ...   
6396  Health_1628976.txt  National Family Caregivers Association (NFCA) ...   
6420  Health_1628833.txt  Rockland Independent Living Center Provides se...   
2919  Health_1614129.txt  Dr. Justin D'Arienzo Private practice located ...   
6231  Health_1628916.txt  Individual Care of Texas Residential care and ...   
6265  Health_1628583.txt  Tucson Adult Care Home A nurse owned and opera...   

      class  
2589      1  
6004      0  
2582      1  
2939      1  
6056      0  
...     ...  
6396      0  
6420      0  
2919      1  
6231      0  
6265      0  

[663 rows x 3 columns]

In [ ]:
df_train['embeddings'] = list(model.encode(df_train.text.to_list()))

df_train

<ipython-input-19-b6eae6c92485>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_train['embeddings'] = list(model.encode(df_train.text.to_list()))


file_name                                               text  \
2589  Health_1614027.txt  Alison Muir - B.A. Hons. Psych. Psychologist l...   
6004  Health_1628690.txt  Delaware Nursing Care Center Skilled nursing a...   
2582  Health_1617262.txt  Behavior OnLine Chat Events Topics of interest...   
2939  Health_1613963.txt  Counsellingsolution.com Provides online counse...   
6056  Health_1628543.txt  Frontier Management Provides assisted living, ...   
...                  ...                                                ...   
6396  Health_1628976.txt  National Family Caregivers Association (NFCA) ...   
6420  Health_1628833.txt  Rockland Independent Living Center Provides se...   
2919  Health_1614129.txt  Dr. Justin D'Arienzo Private practice located ...   
6231  Health_1628916.txt  Individual Care of Texas Residential care and ...   
6265  Health_1628583.txt  Tucson Adult Care Home A nurse owned and opera...   

      class                                         embeddings  
2589      1  [-0.038288515, -0.016204847, 0.0645311, -0.020...  
6004      0  [-0.031521514, -0.028760903, -0.011487525, 0.0...  
2582      1  [0.028935757, 0.010508569, -0.028748892, -0.08...  
2939      1  [-0.02468894, 0.028527418, -0.012190749, -0.02...  
6056      0  [0.10096463, 0.0068017873, 0.033836335, 0.0562...  
...     ...                                                ...  
6396      0  [0.010460184, -0.010522477, 0.028167138, -0.01...  
6420      0  [-0.00892462, 0.0007254818, 0.039617255, -0.00...  
2919      1  [-0.0016316161, -0.040301792, -0.016102491, -0...  
6231      0  [-0.042255383, -0.0025549575, 0.07215384, 0.02...  
6265      0  [-0.027707903, 0.0049154027, 0.0047473633, -0....  

[663 rows x 4 columns]

In [ ]:
df_test['embeddings'] = list(model.encode(df_test.text.to_list()))

df_test

<ipython-input-21-288223521a53>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_test['embeddings'] = list(model.encode(df_test.text.to_list()))


file_name                                               text  \
6161  Health_1629048.txt  Dementia: A Guide For The Caregiver A guide an...   
6167  Health_1628549.txt  Adventist Care Centers Providing long term car...   
6047  Health_1628453.txt  Senior Health Week News and information for se...   
2952  Health_1617358.txt  Vista Continuing Education Online courses for ...   
6341  Health_1628674.txt  Jefferson House Providing long-term care and r...   
...                  ...                                                ...   
6436  Health_1628662.txt  Villa Mirage Elderly board and care, 6-bedhous...   
6070  Health_1628688.txt  Wilton Meadows Rehabilitation and Health Care ...   
6367  Health_1628559.txt  Mountain West Retirement Corporation Retiremen...   
2917  Health_1614367.txt  Elizabeth Fadale, LMHC Private practice locate...   
6443  Health_1628680.txt  Connecticut Elder Reference Guide Infoline 211...   

      class                                         embeddings  
6161      0  [0.016913462, -0.027675265, -0.046555765, -0.0...  
6167      0  [0.03249985, 0.051797815, 0.011143632, 0.04650...  
6047      0  [-0.013294194, 0.021647526, 0.01139685, -0.018...  
2952      1  [0.08416451, -0.05131833, -0.013258689, 0.0034...  
6341      0  [0.031737715, 0.04458959, -0.012021231, -0.001...  
...     ...                                                ...  
6436      0  [0.012460491, -0.017033793, -0.04845216, 0.069...  
6070      0  [0.027699992, -0.07098095, -0.042431783, 0.008...  
6367      0  [0.059199624, 0.02719253, 0.022815082, 0.04951...  
2917      1  [-0.03172243, -0.020222612, 0.013825982, -0.00...  
6443      0  [0.042948768, -0.009476698, 0.044505358, 0.017...  

[337 rows x 4 columns]

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=3,metric="cosine")
knn.fit(np.array(df_train.embeddings.to_list()), df_train['class'])
y_pred = knn.predict(np.array(df_test.embeddings.to_list()))
y_pred

array([1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1,
       1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0,
       0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1,
       1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0,
       1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1,
       0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0,
       1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0,
       0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1,
       1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1,
       0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0,
       1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0,
       1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0,
       1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0,

In [ ]:
from sklearn.metrics import classification_report
print(classification_report(df_test['class'], y_pred))

              precision    recall  f1-score   support

           0       0.96      0.97      0.97       174
           1       0.97      0.96      0.96       163

    accuracy                           0.96       337
   macro avg       0.96      0.96      0.96       337
weighted avg       0.96      0.96      0.96       337

